name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t myapp:test .

      - name: Run Container
        run: docker run -d -p 8080:80 --name myapp myapp:test

      - name: Test health endpoint
        run: |
          sleep 5
          curl -f http://localhost:8080/health
