name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Build Docker Image
      #  run: docker build -t myapp:test .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Tag Docker Image
        run: |
          IMAGE=vblueice/myapp
          VERSION=build-${{ github.run_number }}
          docker build -t $IMAGE:$VERSION .
          docker tag $IMAGE:$VERSION $IMAGE:latest

      - name: Push Docker Image to Docker Hub
        run: |
          IMAGE=vblueice/myapp
          VERSION=build-${{ github.run_number }}
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest

      - name: Deploy to Staging VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ksan
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            IMAGE=vblueice/myapp
            VERSION=build-${{ github.run_number }}
            cd ~/big_tech_deployment
            docker stop myapp || true
            docker rm myapp || true
            docker pull $IMAGE:$VERSION
            docker run -d -p 8080:80 --name myapp $IMAGE:$VERSION


      #- name: Run Container
      #  run: docker run -d -p 8080:80 --name myapp myapp:test

      - name: Test health endpoint
        run: |
          sleep 20
          curl -f http://192.168.56.101:8080/doesnotexist

      - name: Set previous Run Number
        run: echo "PREV_BUILD=$(GITHUB_RUN_NUMBER - 1)" >> $GITHUB_ENV

      - name: Rollback to previous build
        if: failure()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ksan
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: | 
            cd ~/big_tech_deployment
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 8080:80 --name myapp vblueice/myapp:build-${{ env.PREV_BUILD }}

















