name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Build Docker Image
      #  run: docker build -t myapp:test .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: |
          docker build -t vblueice/myapp:test .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push vblueice/myapp:test

      - name: Deploy to Staging VM
        uses: appleboy/ssh-action@0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ksan
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd ~/big_tech_deployment
            docker stop myapp || true
            docker rm myapp || true
            docker pull vblueice/myapp:test || true
            docker run -d -p 8080:80 --name myapp vblueice/myapp:test


      #- name: Run Container
      #  run: docker run -d -p 8080:80 --name myapp myapp:test

      - name: Test health endpoint
        run: |
          sleep 5
          curl -f http://localhost:8080/health
