name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Build Docker Image
      #  run: docker build -t myapp:test .
      
      - name: Set Version
        run: |
          echo "IMAGE=vblueice/myapp" >> $GITHUB_ENV
          echo "BUILD_VERSION=build-${{ github.run_number }}" >> $GITHUB_ENV
          echo "APP_VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV
          echo "IMAGE_TAGS=vblueice/myapp:build-${{ github.run_number }} vblueice/myapp:1.0.${{ github.run_number }} vblueice/myapp:latest" >> $GITHUB_ENV

     # - name: Set Image Tag
     #   run: echo "IMAGE_TAGS=$IMAGE:$BUILD_VERSION $IMAGE:$APP_VERSION $IMAGE:latest" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Tag Docker Image
        run: |
          for tag in $IMAGE_TAGS; do
            docker build -t $tag .
          done

      - name: Push Docker Image to Docker Hub
        run: |
          for tag in $IMAGE_TAGS; do
            docker push $tag
          done

      - name: Deploy to Staging VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ksan
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            docker pull ${{ env.IMAGE }}:${{ env.APP_VERSION }}
            docker run -d -p 8080:80 --name myapp ${{ env.IMAGE }}:${{ env.APP_VERSION }}


      #- name: Run Container
      #  run: docker run -d -p 8080:80 --name myapp myapp:test

      - name: Test health endpoint
        run: |
          sleep 20
          curl -f http://192.168.56.101:8080/health

      - name: Set previous Run Number
        run: echo "PREV_BUILD=$(( ${GITHUB_RUN_NUMBER} - 1 ))" >> $GITHUB_ENV

      - name: Rollback to previous build
        if: failure()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ksan
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: | 
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 8080:80 --name myapp vblueice/myapp:build-${{ env.PREV_BUILD }}

      - name: Create Git Tag
        run : |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $APP_VERSION
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Sanket399/big_tech_deployment.git $APP_VERSION
















